language: python
sudo: false
python:
  - "3.5"
  - "3.5-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8
# command to run tests
script:
  - flake8 appknox
addons:
  apt_packages:
    - pandoc
