language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install pep8
# command to run tests
script:
  - pep8 --ignore=E402 appknox
addons:
  apt_packages:
    - pandoc
